name: ECS Update

on:
  push:
    branches:
      - main

jobs:
  update-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 091888203811.dkr.ecr.eu-west-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          docker build -t nginx:latest .
          docker tag nginx:latest 091888203811.dkr.ecr.eu-west-1.amazonaws.com/nginx:latest
          docker push 091888203811.dkr.ecr.eu-west-1.amazonaws.com/nginx:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          DOCKER_BUILDKIT: 1

      - name: clean up if above command failed
        run: |
         aws s3api delete-bucket --bucket for-app-spec --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        
         
      - name: Update ECS Service
        run: |
          aws s3api create-bucket --bucket for-app-spec --region eu-west-1 --create-bucket-configuration LocationConstraint=eu-west-1
          aws s3 cp ./appspec.yaml s3://for-app-spec/appspec.yaml
          aws deploy create-deployment --cli-input-json file://create-deployment.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          ECS_CLUSTER: nginx-cluster
          ECS_SERVICE: nginx
