name: ECS Update

on:
  push:
    branches:
      - main # Change to your desired branch

jobs:
  update-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 091888203811.dkr.ecr.eu-west-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          docker build -t nginx:latest .
          docker tag nginx:latest 091888203811.dkr.ecr.eu-west-1.amazonaws.com/nginx:latest
          docker push 091888203811.dkr.ecr.eu-west-1.amazonaws.com/nginx:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          DOCKER_BUILDKIT: 1

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster nginx-cluster --service nginx --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          ECS_CLUSTER: nginx-cluster
          ECS_SERVICE: nginx
